### ISSUE TITLE
Hello?

### ISSUE THREAD

**Issue by DevMystical** [accomplis/carding.me#1]
Yo are you yvngxmonkey? If you are add me on discord, I updated my account id

**Comment by coder5010** [comment]
ye it is me

**Comment by coder5010** [comment]
> Yo are you yvngxmonkey? If you are add me on discord, I updated my account id

yeah this my second acc peep the sponsor badge hehe

**Comment by coder5010** [comment]
> Yo are you yvngxmonkey? If you are add me on discord, I updated my account id

my name is x ama add u
